version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "18:00"
    timezone: Europe/London
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: dotenv
    versions:
    - ">= 8.a, < 9"
  - dependency-name: eslint-config-airbnb
    versions:
    - ">= 17.a, < 18"
  - dependency-name: webpack
    versions:
    - ">= 4.a, < 5"
  - dependency-name: ask-sdk
    versions:
    - 2.10.0
  - dependency-name: aws-sdk
    versions:
    - 2.832.0
    - 2.833.0
    - 2.834.0
    - 2.835.0
    - 2.836.0
    - 2.838.0
    - 2.839.0
    - 2.840.0
    - 2.841.0
    - 2.842.0
    - 2.843.0
    - 2.844.0
    - 2.845.0
    - 2.846.0
    - 2.847.0
    - 2.848.0
    - 2.849.0
    - 2.850.0
    - 2.851.0
    - 2.852.0
    - 2.854.0
    - 2.855.0
    - 2.856.0
    - 2.857.0
    - 2.858.0
    - 2.859.0
    - 2.860.0
    - 2.861.0
    - 2.863.0
    - 2.865.0
    - 2.866.0
    - 2.867.0
    - 2.868.0
    - 2.869.0
    - 2.870.0
    - 2.874.0
    - 2.875.0
    - 2.876.0
    - 2.877.0
    - 2.878.0
    - 2.879.0
    - 2.880.0
    - 2.881.0
    - 2.882.0
    - 2.883.0
    - 2.884.0
    - 2.885.0
    - 2.886.0
    - 2.889.0
    - 2.890.0
    - 2.891.0
    - 2.892.0
  - dependency-name: webpack
    versions:
    - 5.18.0
    - 5.19.0
    - 5.20.1
    - 5.20.2
    - 5.21.2
    - 5.22.0
    - 5.23.0
    - 5.24.0
    - 5.24.1
    - 5.24.2
    - 5.24.3
    - 5.24.4
    - 5.26.0
    - 5.26.1
    - 5.26.3
    - 5.27.0
    - 5.27.2
    - 5.28.0
    - 5.29.0
    - 5.30.0
    - 5.31.0
    - 5.31.1
    - 5.31.2
    - 5.32.0
    - 5.35.0
    - 5.35.1
  - dependency-name: serverless
    versions:
    - 2.21.1
    - 2.22.0
    - 2.23.0
    - 2.25.0
    - 2.25.1
    - 2.25.2
    - 2.26.0
    - 2.27.1
    - 2.28.0
    - 2.28.1
    - 2.28.6
    - 2.28.7
    - 2.29.0
    - 2.30.2
    - 2.30.3
    - 2.31.0
    - 2.32.1
    - 2.33.0
    - 2.33.1
    - 2.34.0
    - 2.35.0
    - 2.37.1
    - 2.37.2
  - dependency-name: ytdl-core
    versions:
    - 4.4.5
