service: ${self:custom.config.SERVICE}

custom:
  config: ${file(./src/config.js)}
  stage: ${opt:stage, 'dev'}
  environment:
    STAGE: ${opt:stage, 'dev'}
    TRAKT_CLIENT_ID: ${ssm:/trakt/clientId}
    TRAKT_CLIENT_SECRET: ${ssm:/trakt/clientSecret~true}
  skillId: ${ssm:/alexa/skillId}

provider:
  name: aws
  runtime: nodejs8.10
  stage: ${self:custom.stage}
  environment: ${self:custom.environment}
  region: eu-west-1
  memorySize: 256
  cfLogs: true
  logRetentionInDays: 90
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
        - dynamodb:Query
        - dynamodb:Scan
      Resource:
        - '*'

resources:
  Resources:
    CustomTable:
      Type: 'AWS::DynamoDB::Table'
      DeletionPolicy: Retain
      Properties:
        TableName: ${self:service}-${self:custom.stage}
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST

plugins:
  - serverless-webpack

functions:
  skill:
    name: ${self:service}-${self:custom.stage}
    handler: src/index.handler
    description: Ask Movie Critic to give you movie ratings, give you an overview of a movie, or ask for movie suggestions.
    events:
      - alexaSkill: ${self:custom.skillId}
