export const actionMovie = {
	body: {
		title: 'Aquaman',
		year: 2018,
		ids: {
			trakt: 193968,
			slug: 'aquaman-2018',
			imdb: 'tt1477834',
			tmdb: 297802
		},
		tagline: 'Protector of the Deep',
		overview: "Once home to the most advanced civilization on Earth, the city of Atlantis is now an underwater kingdom ruled by the power-hungry King Orm. With a vast army at his disposal, Orm plans to conquer the remaining oceanic people -- and then the surface world. Standing in his way is Aquaman, Orm's half-human, half-Atlantean brother and true heir to the throne. With help from royal counselor Vulko, Aquaman must retrieve the legendary Trident of Atlan and embrace his destiny as protector of the deep.",
		released: '2018-12-21',
		runtime: 143,
		country: 'us',
		trailer: 'http://youtube.com/watch?v=WDkg3h8PCVU',
		homepage: 'http://www.aquamanmovie.com',
		rating: 7.69733167856035,
		votes: 6446,
		comment_count: 89,
		updated_at: '2019-02-01T08:59:25.000Z',
		language: 'en',
		available_translations: [
			'ar',
			'bg',
			'cs',
			'da',
			'de',
			'el',
			'en',
			'es',
			'fr',
			'he',
			'hu',
			'id',
			'it',
			'ja',
			'ka',
			'ko',
			'lt',
			'lv',
			'ml',
			'nl',
			'no',
			'pl',
			'pt',
			'ro',
			'ru',
			'sk',
			'sr',
			'sv',
			'th',
			'tr',
			'uk',
			'uz',
			'vi',
			'zh'
		],
		genres: [
			'action',
			'fantasy',
			'science-fiction',
			'superhero',
			'adventure'
		],
		certification: 'PG-13'
	}
};

export const horrorMovie = {
	body: {
		title: 'Glass',
		year: 2019,
		ids: {
			trakt: 298686,
			slug: 'glass-2019-298686',
			imdb: 'tt6823368',
			tmdb: 450465
		},
		tagline: 'You Cannot Contain What You Are',
		overview: 'In a series of escalating encounters, security guard David Dunn uses his supernatural abilities to track Kevin Wendell Crumb, a disturbed man who has twenty-four personalities. Meanwhile, the shadowy presence of Elijah Price emerges as an orchestrator who holds secrets critical to both men.',
		released: '2019-01-18',
		runtime: 129,
		country: 'us',
		trailer: 'http://youtube.com/watch?v=95ghQs5AmNk',
		homepage: 'https://www.glassmovie.com',
		rating: 7.31543,
		votes: 1322,
		comment_count: 20,
		updated_at: '2019-01-30T09:03:55.000Z',
		language: 'en',
		available_translations: [
			'ar',
			'bg',
			'cs',
			'da',
			'de',
			'el',
			'en',
			'es',
			'fr',
			'he',
			'hr',
			'hu',
			'it',
			'ko',
			'pl',
			'pt',
			'ru',
			'sk',
			'sr',
			'sv',
			'tr',
			'uk',
			'vi',
			'zh'
		],
		genres: [
			'thriller',
			'superhero',
			'horror',
			'mystery',
			'drama'
		],
		certification: 'PG-13'
	}
};

export const comedyMovie = {
	body: {
		title: 'The Grinch',
		year: 2018,
		ids: {
			trakt: 235711,
			slug: 'the-grinch-2018',
			imdb: 'tt2709692',
			tmdb: 360920
		},
		tagline: 'Scheme big.',
		overview: 'The Grinch hatches a scheme to ruin Christmas when the residents of Whoville plan their annual holiday celebration.',
		released: '2018-11-09',
		runtime: 90,
		country: 'us',
		trailer: 'http://youtube.com/watch?v=vjnqABgxfO0',
		homepage: 'http://grinchmovie.com',
		rating: 7.23409,
		votes: 1508,
		comment_count: 14,
		updated_at: '2019-02-01T08:41:06.000Z',
		language: 'en',
		available_translations: [
			'ar',
			'bg',
			'cs',
			'da',
			'de',
			'el',
			'en',
			'es',
			'et',
			'fr',
			'he',
			'hu',
			'it',
			'ja',
			'ka',
			'ko',
			'lt',
			'lv',
			'nl',
			'no',
			'pl',
			'pt',
			'ro',
			'ru',
			'sk',
			'sr',
			'sv',
			'th',
			'tr',
			'uk',
			'zh'
		],
		genres: [
			'animation',
			'family',
			'comedy',
			'fantasy'
		],
		certification: 'PG'
	}
};
